# Generated by Django 2.2.1 on 2019-05-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speeddetector',
            name='test_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
